# Generated by Django 3.0.8 on 2020-07-27 03:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('urls', '0002_auto_20200727_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='url',
            field=models.URLField(default='www.google.com'),
        ),
        migrations.AlterField(
            model_name='child',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('a3f59218-1407-4ac7-bac3-3512e3cc481b')),
        ),
        migrations.AlterField(
            model_name='parent',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('67af7453-187a-44a6-b79b-44e990e8752f')),
        ),
    ]
