# Generated by Django 3.0.8 on 2020-07-25 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=200)),
                ('status', models.CharField(choices=[('rough_draft', 'Rough Draft'), ('published', 'Published')], default='rough_draft', max_length=20)),
            ],
            options={
                'ordering': ('-title',),
            },
        ),
    ]
