# Generated by Django 3.0.8 on 2020-07-25 12:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('urlshort', '0002_auto_20200725_1222'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shortener',
            new_name='UrlShort',
        ),
    ]
